apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.mongo.name }}-volume"
  labels:
    app: "{{ .Values.mongo.name }}-volume"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
