apiVersion: v1
data:
  client_id: {{ .Values.bot.env.client_id | b64enc }}
  client_secret: {{ .Values.bot.env.client_secret | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.general_secrets_name | quote }}
  namespace: {{ .Values.namespace | quote}}
type: Opaque
